AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SourceBucketName:
    Type: String
  DestinationBucketName:
    Type: String

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName    
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName   

  HitLevelDataAnalizer:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: keyword_performance_analyzer.lambda_handler
      Runtime: python3.9
      MemorySize: 2048
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucketName
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucketName
      Environment:
        Variables:
          DESTINATION_BUCKETNAME: !Ref DestinationBucketName              
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:   
                  - Name: suffix
                    Value: '.tsv'     

Outputs:
  SourceBucketName:
    Value: !Ref SourceBucketName
  DestinationBucketName:
    Value: !Ref DestinationBucketName
